import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import 'mdb-react-ui-kit/dist/css/mdb.min.css'
import { MDBCard, MDBCardBody, MDBCardTitle, MDBCardText, MDBBtn, MDBContainer } from 'mdb-react-ui-kit';


export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
      </Head>
      <div className="container">
        <MDBContainer breakpoint="sm">
            <MDBCard style={{ maxWidth: '22rem' }}>
              <MDBCardBody>
                <MDBCardTitle>Hello devguys this is main page</MDBCardTitle>
                <MDBCardText>
                  Go to {' '}
                  <a href="/api/auth/login">Login</a>
                  <a href="/api/auth/logout">Logout</a>
                </MDBCardText>
              </MDBCardBody>
            </MDBCard>
        </MDBContainer>
      </div>
    </>
  )
}
